"""fix rooms column

Revision ID: f801675e38fc
Revises: 4deaabe705c7
Create Date: 2023-09-22 19:02:58.467950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f801675e38fc'
down_revision: Union[str, None] = '4deaabe705c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('services', sa.JSON(), nullable=True))
    op.drop_column('rooms', 'service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('service', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('rooms', 'services')
    # ### end Alembic commands ###
